### ISSUE TITLE
Communication channel (from background.js to youtubescript.js)

### ISSUE THREAD

**Issue by huntermassey33** [ucsb-cs148-f21/project-t04-youtubevoice#18]
Acceptance criteria:
1.Make sure Backgournd.js cloud receive timestamp from Youtubescript.js.
2.Make sure Youtubescript.js. could receive subtitle from Backgournd.js.

**Comment by kalebkwok** [comment]
Acceptance criteria: 
1.Make sure Backgournd.js cloud receive timestamp from Youtubescript.js.
2.Make sure   Youtubescript.js. could receive subtitle from Backgournd.js.

**Comment by notadgupta** [comment]
Implemented!
