### ISSUE TITLE
Add user interface for turning on extension

### ISSUE THREAD

**Issue by huntermassey33** [ucsb-cs148-f21/project-t04-youtubevoice#25]
Criteria:
Adds a popup and a button to start the voice changing. (Which includes the assumption that once we add it, it also works)

**Comment by notadgupta** [comment]
I suppose this is creating additional issues. This is identical to #25. In this one the other half of the team is assigned and both are posted on the Kanban board. I'm merging this with #25.

**Comment by notadgupta** [comment]
We need to integrate the functionally to the button merged from #28 which is now closed, I am adding myself to monitor the progress.

**Comment by encombhat** [comment]
Related: #29
