### ISSUE TITLE
Multiple tab support

### ISSUE THREAD

**Issue by encombhat** [ucsb-cs148-f21/project-t04-youtubevoice#32]
Add support for multiple active tabs.

Currently the extension breaks catastrophically if multiple Youtube videos are opened.

**Comment by encombhat** [comment]
And the original subtitle seeking implementation is broken somehow.

**Comment by notadgupta** [comment]
How is this **in progress**? Why do we _need_ this? Simple questions to ask yourself.

Is this part of any core functionality, _I don't think so..._ therefore just put some limiter and warning to the user if multiple tabs are opened, save the time for more necessary work?

Comments? Thoughts?

**Comment by notadgupta** [comment]
Closed, since apparently done...?
