### ISSUE TITLE
Add text field for API key in UI

### ISSUE THREAD

**Issue by huntermassey33** [ucsb-cs148-f21/project-t04-youtubevoice#42]

**Comment by notadgupta** [comment]
Should take ~20 min

**Comment by notadgupta** [comment]
Remember we need two text fields, one for OAuth 2.0 and one for API key. Input must be verified and sanitized to avoid filler content from being dumped by the user.

Stretch goal - Validate the API key immediately when user enters and scream to the user if such is invalid, ~45 min

**Comment by notadgupta** [comment]
Guess we don't need this. Add this as a separate branch in case we may need to revert to this solution in the future, however without any suck-cost fallacy we must now close this without anything
