### ISSUE TITLE
Organize the .js files into folders and fix dependency graphs

### ISSUE THREAD

**Issue by notadgupta** [ucsb-cs148-f21/project-t04-youtubevoice#46]
Everything spilled in the root folder looks quite messy, indeed. Manifest and other files may need to be modified as new folders are created designating the subfiles of each.

Should take ~20 min

**Comment by huntermassey33** [comment]
Created user_interface, background_scripts and content_scripts folders, added their respective files, and modified manifest accordingly.

**Comment by notadgupta** [comment]
Always comment why this is re-opened. Assign someone to review or help you and work on it as need be.

**Comment by notadgupta** [comment]
Closed, since not needed anymore
